[package]
name = "spidermonkey-sys"
version = "0.0.1"
description = "Low level bindings to spidermonkey"
edition.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
